### PR TITLE
Create fr-FR.plg_content_uploader.ini

### PR DESCRIPTION
**Pull request by MATsxm**
I will finish it and check tomorrow

### CODE REVIEW

**Comment by MATsxm** [comment]
Done! :smiley:

**Comment by dgrammatiko** [comment]
Thank you @MAT978 Beers on me on our next meeting (JAB2016?) 🍺🍺

**Comment by MATsxm** [comment]
anytime for both fr-FR translations + :beers:

**Comment by dgrammatiko** [comment]
The other one had some conflicts, so I copy pasted the strings. Once again huge thanks! 🍺

**Pull request merged**
